FROM ubuntu:16.10
COPY  docs  /home/docs  
COPY  nginx.conf /etc/nginx/nginx.conf
COPU  default.conf  /etc/nginx/conf.d/default.conf

RUN apt-get update \
    && apt-get upgrade -y \ 
    && apt-get install --no-install-recommends nginx ruby gcc make -y \
    && apt-get autoclean  \
    && apt-get clean  \
    && apt-get purge  \
    && apt-get autoremove  \ 
    && rm -rf /var/cache/*  \
    && dpkg -l |grep ^rc|awk '{print $2}' |sudo xargs dpkg -P   \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp 
    && rm -rf /usr/share/doc/* /usr/share/man/* /usr/share/info/*  

EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"]