name: Rancher 中文文档(社区版)(实验)
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  toc_levels: 2..4
incremental: true
permalink: pretty
safe: false
lsi: false
url: https://docs.xtplayer.cn
keep_files: [ "v1.6"]
# Component versions -- address like site.docker-ce_stable_version
rancher_stable_version: "1.6.10"
docker-ce_edge_version: "17.09"
docker-ee_version: "17.06"
compose_version: "1.16.1"
machine_version: "0.12.2"
distribution_version: "2.6"

collections:
  samples:
    output: true

jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration

gems:
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-relative-links

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: docs
      defaultassignee: johndmulhausen
      toc_min: 2
      toc_max: 4
      tree: true



# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
